apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: chonmon
  name: chonmon-controller
spec:
  replicas: 2
  selector:
    name: chonmon
  template:
    metadata:
      labels:
        name: chonmon
    spec:
      containers:
      - image: chonmon:3
        name: chonmon
        volumeMounts:
        - mountPath: /data/webroot/chonmon.todo.vn/
          name: chonmon-volume
        ports:
        - containerPort: 80
          name: http-server
        
      volumes:
      - name: chonmon-volume
        hostPath:
          path: /data/webroot/chonmon.todo.vn/