apiVersion: v1
kind: Service
metadata:
  name: chonmon
  labels:
    name: chonmon
spec:
  type: NodePort
  ports:
    - nodePort: 30801
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: chonmon